# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the zh_CN branch
  push:
    branches: [ zh_CN ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install software
        run: sudo apt update && sudo apt-get install -y make texlive-xetex

      # Runs a set of commands using the runners shell
      - name: build my resume
        run: |
          make
      - name: upload to my server
        run: printf "%s" "${{ secrets.DEPLOY_KEY }}" > ${SSH_PRIVATE} && chmod 600 ${SSH_PRIVATE} && rsync -avzW resume.pdf resume_en.pdf ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/data/hexo --rsh "ssh -p ${{ secrets.DEPLOY_PORT }} -i ${SSH_PRIVATE} -o StrictHostKeyChecking=no"
        env:
          SSH_PRIVATE: ../id_rsa.pem
